Improvement/Dashboard redesign feedback
weglot/design pull request #35
Opened 2023-08-22 12:36 UTC by dtrinh-weglot

Issue : https://github.com/weglot/core/issues/3670

2023-08-22 12:49 UTC, floranpagliai requested changes

2023-08-22 12:49 UTC, floranpagliai commented on scss/_card.scss
> +.card {
Est ce que la solution ça ne serai pas plutôt de faire différemment en html ? Plutôt que du css custom ?

2023-08-22 12:58 UTC, dtrinh-weglot commented on scss/_card.scss
> +.card {
En HTML ça impliquerait de repasser sur tout les tableaux non ? (Je n'ai pas trop étudié la question)
Ce CSS corrige un cas très spécifique : 
<img width="618" alt="image" src="https://github.com/weglot/design/assets/118731144/0c5eedcc-90e1-4e36-89b6-afcc752768f2">
 
<img width="903" alt="image" src="https://github.com/weglot/design/assets/118731144/84a5b359-77ee-4acc-be23-53dc1102d96c">

Sans le fix, le premier th a le top-left-corner + le dernier th a le top-right-corner qui ne sont pas arrondis : 
<img width="698" alt="image" src="https://github.com/weglot/design/assets/118731144/630b211a-db08-413d-9588-f0f814ed5a94">
<img width="430" alt="image" src="https://github.com/weglot/design/assets/118731144/c3bfb79d-620b-4f6c-8bee-d34cfaf070d3">

2023-08-23 08:56 UTC, dtrinh-weglot commented
> C'est lié à une issue non ?

Oui, c'est lié à la https://github.com/weglot/core/issues/3670

2023-08-29 08:27 UTC, VincentLanglet commented on scss/_card.scss
> +.card {
Ca me parait pas choquant d'avoir un css qui gère ce "conflict" de manière général.

2023-08-29 08:28 UTC, VincentLanglet approved these changes

2023-08-29 08:45 UTC, floranpagliai requested changes

2023-08-29 08:45 UTC, floranpagliai commented on scss/_card.scss
> +.card {
Solution beaucoup plus simple, ajouter `overflow: hidden;` sur la class `.table`.

2023-08-29 08:59 UTC, floranpagliai commented
> @floranpagliai
> 
> ```
> .card {
>   .table {
>     overflow: hidden;
>   }
> }
> ```
> 
> Cela fonctionne pour le cas où le tableau est collé en haut de la card mais ça ne rend plus le haut du tableau "rectangle" dans ce cas là : <img alt="image" width="815" src="https://user-images.githubusercontent.com/118731144/263959420-a73a8064-3e83-48c5-a154-b0ce3213a7f7.png">


Ha oui pardon met le au niveau de `.card` en fait:

```
.card {
    overflow: hidden;
}
```

2023-08-29 09:06 UTC, VincentLanglet approved these changes

2023-08-29 13:13 UTC, merged