Improvement/ProgressBar Round Alternative Design
weglot/design pull request #54
Opened 2024-05-21 13:26 UTC by EtienneDh

![image](https://github.com/weglot/design/assets/19950331/9e75f103-5ad0-4cf6-96b1-f0f36c9b1d29)

2024-05-21 13:27 UTC, EtienneDh commented
Hello @floranpagliai. J'ai ajouté une 'progress-bar-round-secondary' pour essayer de coller au maximum au design de Rémy

2024-05-21 14:48 UTC, floranpagliai requested changes

2024-05-21 19:28 UTC, floranpagliai commented on scss/_progress.scss
> +            background: conic-gradient(#fff calc(var(--percentage) * 1%), $gray-400 0);
Le $progress-bg ça allait pas ? Vu que c'est le $gray-400 dérrière

2024-05-21 19:30 UTC, floranpagliai commented
Après réflexion je me dit qu'on pourrait faire la propal avec la progress bleu avec comme argument que comme ça on respecte la charte couleur des autre progress.

2024-05-22 12:41 UTC, EtienneDh commented
> Après réflexion je me dit qu'on pourrait faire la propal avec la progress bleu avec comme argument que comme ça on respecte la charte couleur des autre progress.

Pourquoi pas mais étant donné que Rémy ne sera pas de retour avec un moment, on ne pourra pas valider avec lui, il faudrait pas que ça soit trop bloquant pour la suite du dev

2024-05-23 09:15 UTC, merged