Improvement/Remove caret in dropdown component
weglot/design pull request #64
Opened 2024-10-02 13:50 UTC by dtrinh-weglot

Proposition de suppression du `caret` dans les dropdown qu'on a.

En effet, l'alignement de ce `caret` est source de complexité car il peut être à gauche, à droite, au milieu, à gauche mais pas trop à gauche, à droite mais pas trop à droite, verticalement... du coup cette PR vise supprimer ce `caret`.

On a déjà des comportements similaires sur des SaaS tels que Github : 
<img width="357" alt="image" src="https://github.com/user-attachments/assets/80082efd-d5b8-469b-bbf7-b3bab390d384">

Voici un visuel de ce que ça pourrait donner ainsi que la page de documentation associée : 

![image](https://github.com/user-attachments/assets/ada4de81-a2dc-4ca8-87a4-b0907ae6ab1d)

![image](https://github.com/user-attachments/assets/faddc794-ea8e-4c8c-b7c8-2077bfa92828)

2024-10-02 14:44 UTC, VincentLanglet commented on docs/404.html
> +    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></s
Pourquoi t'as besoin de ça ? Le package.json est pas utilisé ?

2024-10-02 14:44 UTC, VincentLanglet commented on docs/docs/components/alerts.html
> +
c'est auto généré ces lignes blanches ?

2024-10-02 14:45 UTC, VincentLanglet approved these changes

2024-10-02 14:45 UTC, dtrinh-weglot commented on docs/404.html
> +    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></s
Je crois pas que le JS marche correctement

2024-10-02 14:45 UTC, dtrinh-weglot commented on docs/docs/components/alerts.html
> +
Oui pas touché aux alerts

2024-10-03 13:26 UTC, floranpagliai commented on scss/bootstrap/_variables.scss
> -$dropdown-item-padding-x: 1.5rem !default;
Quid du default ?

2024-10-03 13:46 UTC, dtrinh-weglot commented on scss/bootstrap/_variables.scss
> -$dropdown-item-padding-x: 1.5rem !default;
Faut le laisser ou l'enlever ? 
<img width="1130" alt="image" src="https://github.com/user-attachments/assets/be22920e-10b8-4528-b7f7-9839e30a42d4">

2024-10-03 13:53 UTC, floranpagliai commented on scss/bootstrap/_variables.scss
> -$dropdown-item-padding-x: 1.5rem !default;
C'est ma question justement, c'est quoi la valeur par defaut 1.5rem ou spacer ?

2024-10-03 13:58 UTC, dtrinh-weglot commented on scss/bootstrap/_variables.scss
> -$dropdown-item-padding-x: 1.5rem !default;
Ah j'avais mal compris je pensais que tu parlais du `!default`
J'ai regardé sur https://github.com/twbs/bootstrap/blob/v4.6.2/scss/_variables.scss et c'est : 
```
$dropdown-item-padding-y:           .25rem !default;
$dropdown-item-padding-x:           1.5rem !default;
```

j'ai repush

2024-10-03 13:59 UTC, floranpagliai commented on scss/bootstrap/_variables.scss
> +$dropdown-item-padding-x: $spacer !default;
```suggestion
$dropdown-item-padding-x: $spacer;
```

Très important la gestion des default pour quand il faudra passer sur BS5 !

2024-10-03 14:00 UTC, floranpagliai requested changes

2024-10-03 14:00 UTC, floranpagliai commented on scss/bootstrap/_variables.scss
> +$dropdown-item-padding-y: $spacer * 0.25 !default;
```suggestion
$dropdown-item-padding-y: $spacer * 0.25;
```

Pas sur de comprendre pk essayer de se baser sur le spacer ici

2024-10-03 14:14 UTC, floranpagliai requested changes

2024-10-03 14:14 UTC, floranpagliai commented on scss/bootstrap/_variables.scss
> +$dropdown-item-padding-y: 0.25rem;
```suggestion
$dropdown-item-padding-y: 0.25rem !default;
```

On vas y arriver ^^

2024-10-03 14:14 UTC, floranpagliai commented on scss/bootstrap/_variables.scss
> +$dropdown-item-padding-x: 1.5rem;
```suggestion
$dropdown-item-padding-x: 1.5rem !default;
```

2024-10-07 07:49 UTC, floranpagliai approved these changes

2024-10-07 07:50 UTC, merged