Improvement/6000 Select2 as action design inconsistency
weglot/design pull request #89
Opened 2024-11-27 15:28 UTC by dtrinh-weglot

Fix https://github.com/weglot/core/issues/6000

2024-11-27 16:06 UTC, VincentLanglet approved these changes

2024-11-28 12:25 UTC, floranpagliai requested changes

2024-11-28 12:25 UTC, floranpagliai commented on scss/plugins/select2.scss
> +    color: $blue;
Plutot utiliser $body-emphasis-color ou $headings-color

2024-11-28 12:25 UTC, floranpagliai commented on scss/plugins/select2.scss
>      .select2-selection__rendered {
Pareil ici

2024-11-28 12:47 UTC, VincentLanglet approved these changes

2024-11-28 12:48 UTC, merged